name: da_fare
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.10
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.1.10
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  path: ^1.8.0
  font_awesome_flutter: ^9.2.0
  line_icons: ^2.0.1
  google_fonts: ^2.1.1
  iconly: ^1.0.1
  intl: ^0.17.0
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.18.2
  flutter_riverpod: ^1.0.3
  percent_indicator: ^4.0.0
  flutter_sound_lite: ^8.5.0
  permission_handler: ^8.3.0
  flutter_neat_and_clean_calendar: ^0.3.1+14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

